apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
        version: v1
    spec:
      containers:
        - name: back
          image: kravuar/dz21back:latest
          env:
            - name: SPRING_R2DBC_URL
              value: r2dbc:mysql://mysql:3306/json-app-db
            - name: SPRING_R2DBC_USERNAME
              value: root
            - name: SPRING_R2DBC_PASSWORD
              value: pass
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: back
spec:
  selector:
    app: back
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP