apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
        version: v1
    spec:
      containers:
        - name: front
          image: kravuar/dz21front:latest
          env:
            - name: REACT_APP_BACKEND_URL
              value: https://ad68-95-25-60-157.ngrok-free.app/back/json
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  selector:
    app: front
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
