apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: front
spec:
  hosts:
    - front
  http:
    - route:
        - destination:
            host: front
            subset: v1
          weight: 50
        - destination:
            host: front
            subset: v2
          weight: 50

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: front
spec:
  host: front
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2