---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-new
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
        version: v2
    spec:
      containers:
        - name: front
          image: kravuar/dz21front-new:latest
          env:
            - name: REACT_APP_BACKEND_URL
              value: / # TODO: placeholder, insert ngrok
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  selector:
    app: front
  ports:
    - port: 3000
  type: ClusterIP
