# Мдееееееееееееееееееееееееееееееее

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-api
  namespace: app
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway-service
  namespace: app
spec:
  hosts:
    - "*"
  gateways:
    - gateway-api
  http:
    - match:
        - uri:
            prefix: "/back/" # extra '/' here as a workaround, without it results in '//' prefix after rewrite
      route:
        - destination:
            host: back
            port:
              number: 8080
      rewrite:
        uri: "/"
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: front
            port:
              number: 3000