spring:
  r2dbc:
    url: r2dbc:h2:mem:///~/db/user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    web: debug